In [1]:
import numpy as np
import scipy as sp

from numpy.linalg import norm

import matplotlib.pyplot as plt

_ = lambda *x: np.array([*x])

# ADDLIN. HW2
Михайло Корешков

## Завдання 1
Записати 5 різних прикладів векторних просторів

### Приклад 1.
$M_{n\times n}(\mathbb{Z}_k)$ - простір матриць над скінченним полем. Широко використовується у криптографії.

### Приклад 2.
$P_n(\mathbb{Z}_k)$ - простір поліномів над скінченним полем. Широко використовується у криптографії та кодуванні. Мій улюблений приклад застосування це алгоритм чексуми CRC.

### Приклад 3.
Елементи дотичного до точки простору у многовиді. Доведення того, що цей простір дійсно лінійний, не очевидне.



---

## Завдання 2 (6)
Чи можуть 5 векторів в одному просторі бути лінійно залежними, а в іншому - лінійно незалежними?

**Приклад 1**  
$a = (1,2), b = (2,1)$
1. Нехай $a, b \in \mathbb R^2$, тоді $a,b$ - лінійно незалежні
2. Нехай $a, b \in \mathbb Z/3Z$, тобто кільце лишків від ділення на 3, тоді $a+b = 0$, тобто $a,b$ - лінійно залежні

**Приклад 2**  
Нехай $a,b \in B \subset A$, $A$ - лінійний простір над полем $F$, $B$ - його лінійний підпростір з ттими самими операціями.  
Припустимо, що $a,b$ лінійно залежні в $B$.
Це означає, що $\exists \alpha,\beta\in F: a\alpha + b\beta = 0$.  
Зверну увагу, що $0\in A, 0 \in B, 0_A = 0_B$.
А тоді $a\alpha + b\beta = 0$ справедливо і для простору $A$. Отже, $a$ та $b$ лінійно залежні і в $A$.


## Завдання 3 (10)
Приклади лінійно незалежних систем

1. 2 непропорнійні вектори
2. 2 непропорційні вектори та їх векторний добуток в $\mathbb R^3$
3. власні вектори лінійного оператора


## Завдання 4 (23)

> Довести що система функцій $S = \{f_1(x), ..., f_n(x)\}$ над скінченним полем з $p$ елементами є лінійно залежною для $n>p$.

Якщо коротко, то у полі не вистачає точок для перевірки лінійної незаленості і приходиться брати повторні точки, що дасть однакові стовпчики.

З визначення лінійної залежності функцій, квадратна матриця $B = (f_i(h_j))$ має бути невиродженою для деяких $h_1, h_2, ..., h_n \in F_p$. Значення $h_j$ будуть повторюватись. Тому 
$$A = \begin{pmatrix}
f_1(1) & f_1(2) & ... & f_1(p) & f_1(h_1) & f_1(h_2) & ... & f_1(h_{n-p})\\
f_2(1) & f_2(2) & ... & f_2(p) & f_2(h_1) & f_2(h_2) & ... & f_2(h_{n-p})\\
\vdots & \vdots &     & \vdots & \vdots   & \vdots   & ... & \vdots  \\
f_n(1) & f_n(2) & ... & f_n(p) & f_n(h_1) & f_n(h_2) & ... & f_n(h_{n-p})\\
\end{pmatrix}$$ 
де $h_1, ..., h_{n-p}$ це повтори деяких значень від 1 до p.

Але тоді маємо однакові стовпці, а отже $\det A = 0$

## Завдання 5 (22)
Чи можна задати набір функцій на $[0;1]$ так, щоб вони були лінійно незалежними, але $\det G = 0\;(a.s.)$ при випадковому виборі $x_i$?

Нехай $f,g \in C[0;1]$ - лінійно незалежні.  
Тоді 
$$\exists x,y\in[0,1]: f(x)g(y) - f(y)g(x) = a \ne 0$$
З неперервності f та g
$$\forall \epsilon>0: \exists \delta>0: \forall h, |h|<\delta: (a-\epsilon) < f(x+h)g(y)-f(y)g(x+h) < (a+\epsilon) $$
Нехай $\epsilon = a$
$$\exists \delta>0: \forall h, |h|<\delta: 0 < f(x+h)g(y)-f(y)g(x+h) < 2a$$

Тоді маємо інтервал $(x-\delta;x+\delta)$ в якому $f(x)g(y) - f(y)g(x) \ne 0$.  
Але тоді $P(\det G \ne 0) \ge 2\delta > 0$

Отже, таке неможливо для неперервних функцій.

### Приклад - неперервна фукнція на [-1;1]
Розглянемо $f(x) = x, g(x) = |x|$
$$x|y|-y|x| = \begin{cases}
0, & xy=0\\
xy-yx = 0, & xy>0\\
xy+yx = 2xy < 0, & x<0, y>0\\
-xy-yx = -2xy > 0, & x>0, y<0\\
\end{cases}$$

Тоді $P(G=0) = \frac{\mu(xy>=0)}{\mu([-1;1])} = 1/4 \ne 1$

## Завдання 6 (практика 9)
для будь якого вектора $x$ система $x = \alpha_1v_1 + ... + \alpha_s v_s$ має розв'язок відносно $\alpha$. З цього випливає повнота системи $v_1, ..., v_s$.
Оскільки координати складають трикутну матрицю (тобто з повним рангом), то вектори $v_1, ..., v_s$ - лінійно незалежні.

Відомо, що критерій базису це повнота та лінійна незалежність, отже довели, що це базис.

## Завдання 7 (практика 10)
$V = S((1,2,3,4,5,6), (1,1,2,3,4,6)) = S(a,b)$  
$W = S((1,-1,1,-1,1,1), (2,1,2,1,2,3)) = S(c,d)$  

Знайти базис перетину $V\cap W$

$$q \in V \implies \exists x,y: ax+by = q$$
$$p \in W \implies \exists x,y: cx+dy = p$$

Let $A = ( a, b )$, $B = ( c, d )$ - матриці.

1. Параметризуємо обидва простори. Представляємо їх у вигляді overdetermined system (рівнянь більше ніж змінних). Змінними будуть деякі параметри $u$ підпростору, які в результаті зникнуть  
    $$\vec x = A \vec u$$
2. Розв'язуємо систему відносно $\vec x$ таким чином, щоб отримати рівняння $A_1 \vec x = 0$. Один варіант формального запису цієї операції -- через LU-факторизацію:
    $$A = PLU$$
    $$\vec x = PLU \vec u$$
    При чому $U$ - висока верхня трикутна, $L$ - квадратна, $P$ - матриця перестановок координат.  
    Далі маємо
    $$L^{-1}P^T\vec x = U\vec u$$
    При чому $U$ - висока верхня трикутна, а тому всі елементи вектора $U\vec u$  після деякого номеру будуть нулями. Відкинемо перші рядки в матрицях $L^{-1}$ та $U$ (ті рядки, що відповідають ненульовим елементам) і отримаємо
    $$L^{-1}_1P^T\vec x = 0$$
    Тобто, привели рівняння до бажаного вигляду $A_1\vec x = 0$


    *Зауваження:* 
    > В даному випадку може бути доцільніше використати QR факторизацію. Тоді
    >$$\vec x = A \vec u = QR \vec u$$
    >$$Q^T\vec x = R \vec u$$
    >Відкидаємо матрицю $R$, відкидаємо перші рядки $Q^T$. Останні рядки $Q^T$ буде нашим $A_1$ для рівняння $A_1\vec x = 0$

    Представленням підпростору через систему лінійних рівнянь буде матриця коефіцієнтів $A_1 = L^{-1}_1P^T$ або $A_1 = Q^T$

3. Залишається знайти розв'язки рівняння 
    $$\begin{pmatrix}A_1 \\ B_1\end{pmatrix} \vec x = C\vec x = 0$$
    Фундаментальна система розв'язків дасть нам базис підпростору перетину просторів A та B  

    Програмно я реалізував це через LU факторизацію утвореної матриці $C$.
    $$C\vec x = PLU\vec x = 0$$
    При чому $L$ маає бути високою.  
    

In [42]:
from sympy import symbols

a = _(1,2,3,4,5,6)
b = _(1,1,2,3,4,6)
c = _(1,-1,1,-1,1,1)
d = _(2,1,2,1,2,3)
A = np.vstack([a,b]).T
B = np.vstack([c,d]).T

x,y = symbols('x y')

A, B

(array([[1, 1],
        [2, 1],
        [3, 2],
        [4, 3],
        [5, 4],
        [6, 6]]),
 array([[ 1,  2],
        [-1,  1],
        [ 1,  2],
        [-1,  1],
        [ 1,  2],
        [ 1,  3]]))

In [104]:
DD = np.vstack([a,b,c,d])
np.linalg.matrix_rank(DD)

4

In [70]:
Q_A, R_A = sp.linalg.qr(A, mode='full')

r = R_A.shape[1]
A1 = Q_A.T[r:]

Q_A.round(4), R_A.round(4), A1.round(4)

(array([[-0.1048,  0.1132, -0.2241, -0.3506, -0.477 , -0.7587],
        [-0.2097, -0.5095, -0.4711, -0.3926, -0.3141,  0.4709],
        [-0.3145, -0.3963,  0.8163, -0.191 , -0.1983, -0.0438],
        [-0.4193, -0.2831, -0.1763,  0.7975, -0.2286, -0.157 ],
        [-0.5241, -0.1698, -0.1689, -0.2139,  0.7411, -0.2701],
        [-0.629 ,  0.6794,  0.0445, -0.0686, -0.1818,  0.3211]]),
 array([[-9.5394, -8.0718],
        [ 0.    ,  1.3587],
        [ 0.    ,  0.    ],
        [ 0.    ,  0.    ],
        [ 0.    ,  0.    ],
        [ 0.    ,  0.    ]]),
 array([[-0.2241, -0.4711,  0.8163, -0.1763, -0.1689,  0.0445],
        [-0.3506, -0.3926, -0.191 ,  0.7975, -0.2139, -0.0686],
        [-0.477 , -0.3141, -0.1983, -0.2286,  0.7411, -0.1818],
        [-0.7587,  0.4709, -0.0438, -0.157 , -0.2701,  0.3211]]))

In [71]:
# система, що описує підпростір A
A1.round(4) @ _(*symbols('x1 x2 x3 x4 x5 x6'))

array([-0.2241*x1 - 0.4711*x2 + 0.8163*x3 - 0.1763*x4 - 0.1689*x5 + 0.0445*x6,
       -0.3506*x1 - 0.3926*x2 - 0.191*x3 + 0.7975*x4 - 0.2139*x5 - 0.0686*x6,
       -0.477*x1 - 0.3141*x2 - 0.1983*x3 - 0.2286*x4 + 0.7411*x5 - 0.1818*x6,
       -0.7587*x1 + 0.4709*x2 - 0.0438*x3 - 0.157*x4 - 0.2701*x5 + 0.3211*x6],
      dtype=object)

In [73]:
Q_B, R_B = sp.linalg.qr(B, mode='full')

r = R_B.shape[1]
B1 = Q_B.T[r:]

Q_B.round(4), R_B.round(4), B1.round(4)

(array([[-0.4082, -0.2164, -0.4673,  0.1679, -0.4673, -0.5671],
        [ 0.4082, -0.5626, -0.0182, -0.674 , -0.0182, -0.2489],
        [-0.4082, -0.2164,  0.85  , -0.0104, -0.15  , -0.2035],
        [ 0.4082, -0.5626,  0.0764,  0.7107,  0.0764,  0.0054],
        [-0.4082, -0.2164, -0.15  , -0.0104,  0.85  , -0.2035],
        [-0.4082, -0.476 , -0.1745, -0.1103, -0.1745,  0.7305]]),
 array([[-2.4495, -2.8577],
        [ 0.    , -3.8514],
        [ 0.    ,  0.    ],
        [ 0.    ,  0.    ],
        [ 0.    ,  0.    ],
        [ 0.    ,  0.    ]]),
 array([[-0.4673, -0.0182,  0.85  ,  0.0764, -0.15  , -0.1745],
        [ 0.1679, -0.674 , -0.0104,  0.7107, -0.0104, -0.1103],
        [-0.4673, -0.0182, -0.15  ,  0.0764,  0.85  , -0.1745],
        [-0.5671, -0.2489, -0.2035,  0.0054, -0.2035,  0.7305]]))

In [74]:
# система, що описує підпростір B
B1.round(4) @ _(*symbols('x1 x2 x3 x4 x5 x6'))

array([-0.4673*x1 - 0.0182*x2 + 0.85*x3 + 0.0764*x4 - 0.15*x5 - 0.1745*x6,
       0.1679*x1 - 0.674*x2 - 0.0104*x3 + 0.7107*x4 - 0.0104*x5 - 0.1103*x6,
       -0.4673*x1 - 0.0182*x2 - 0.15*x3 + 0.0764*x4 + 0.85*x5 - 0.1745*x6,
       -0.5671*x1 - 0.2489*x2 - 0.2035*x3 + 0.0054*x4 - 0.2035*x5 + 0.7305*x6],
      dtype=object)

In [75]:
C = np.vstack([A1, B1])
C.round(4)

array([[-0.2241, -0.4711,  0.8163, -0.1763, -0.1689,  0.0445],
       [-0.3506, -0.3926, -0.191 ,  0.7975, -0.2139, -0.0686],
       [-0.477 , -0.3141, -0.1983, -0.2286,  0.7411, -0.1818],
       [-0.7587,  0.4709, -0.0438, -0.157 , -0.2701,  0.3211],
       [-0.4673, -0.0182,  0.85  ,  0.0764, -0.15  , -0.1745],
       [ 0.1679, -0.674 , -0.0104,  0.7107, -0.0104, -0.1103],
       [-0.4673, -0.0182, -0.15  ,  0.0764,  0.85  , -0.1745],
       [-0.5671, -0.2489, -0.2035,  0.0054, -0.2035,  0.7305]])

In [92]:
L_C = sp.linalg.lu(C)[1]
L_C.round(4)

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.4621,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2954,  1.    ,  1.    ,  0.    ,  0.    ,  0.    ],
       [ 0.6287,  1.    ,  0.    ,  1.    ,  0.    ,  0.    ],
       [ 0.616 ,  0.5052,  0.9633, -0.6968,  1.    ,  0.    ],
       [ 0.7475,  0.9848, -0.0025,  0.7366, -0.8579,  1.    ],
       [ 0.616 ,  0.5052, -0.0367,  0.3032,  1.    ,  0.9142],
       [-0.2214,  0.9337,  0.1393, -0.003 ,  0.021 ,  0.4141]])

In [86]:
sp.linalg.inv(U_C).round(4)

array([[-1.318 , -1.0172, -0.2315, -0.4466, -0.    ,  0.457 ],
       [ 0.    , -1.6388, -0.2799, -1.146 ,  1.3189,  0.5799],
       [ 0.    ,  0.    ,  1.    , -1.    ,  1.3189,  1.0368],
       [ 0.    ,  0.    ,  0.    , -1.    ,  1.3189,  1.494 ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  1.3189,  1.9512],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  2.7427]])

In [99]:
Q,R = sp.linalg.qr(C, mode='full')
Q.round(3), R.round(3)

(array([[-0.169, -0.419,  0.585,  0.331,  0.165,  0.029,  0.443, -0.346],
        [-0.264, -0.342, -0.246, -0.59 ,  0.129,  0.391,  0.435,  0.215],
        [-0.359, -0.266, -0.251,  0.525, -0.284,  0.53 , -0.299,  0.101],
        [-0.571,  0.46 , -0.034, -0.169,  0.248,  0.147, -0.158, -0.569],
        [-0.352,  0.003,  0.658, -0.299, -0.191, -0.024, -0.375,  0.42 ],
        [ 0.126, -0.62 , -0.092, -0.319, -0.045, -0.174, -0.503, -0.452],
        [-0.352,  0.003, -0.167, -0.049, -0.723, -0.45 ,  0.316, -0.14 ],
        [-0.427, -0.203, -0.254,  0.21 ,  0.502, -0.557, -0.081,  0.315]]),
 array([[ 1.328,  0.061, -0.152,  0.025, -0.188, -0.311],
        [ 0.   ,  1.1  , -0.194, -0.652, -0.127,  0.12 ],
        [ 0.   ,  0.   ,  1.212, -0.266, -0.411, -0.183],
        [ 0.   ,  0.   ,  0.   , -0.875,  0.469,  0.155],
        [ 0.   ,  0.   ,  0.   ,  0.   , -1.021,  0.661],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.379],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],


In [100]:
np.linalg.matrix_rank(C)

6