In [1]:
import numpy as np
import scipy as sp

# Перпендикуляр до системи векторів

In [4]:
A = np.array([
    [0,0,0,0],
    [1,2,3,4],
    [5,6,7,8],
    [9,1,1,1]
])

In [5]:
A11 = A[1:,1:]
A11

array([[2, 3, 4],
       [6, 7, 8],
       [1, 1, 1]])

In [7]:
A12 = A[1:,(0,2,3)]
A12

array([[1, 3, 4],
       [5, 7, 8],
       [9, 1, 1]])

In [8]:
A13 = A[1:,(0,1,3)]
A13

array([[1, 2, 4],
       [5, 6, 8],
       [9, 1, 1]])

In [9]:
A14 = A[1:,(0,1,2)]
A14

array([[1, 2, 3],
       [5, 6, 7],
       [9, 1, 1]])

In [11]:
n = np.array([np.linalg.det(x) for x in (A11,A12,A13,A14)])
n

array([ 1.48029737e-16, -3.20000000e+01, -6.40000000e+01, -3.20000000e+01])

In [21]:
B = np.vstack([n, A[1:]])
B

array([[ 1.48029737e-16, -3.20000000e+01, -6.40000000e+01,
        -3.20000000e+01],
       [ 1.00000000e+00,  2.00000000e+00,  3.00000000e+00,
         4.00000000e+00],
       [ 5.00000000e+00,  6.00000000e+00,  7.00000000e+00,
         8.00000000e+00],
       [ 9.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00]])

In [25]:
np.linalg.det(A), np.linalg.det(B)

(0.0, 2048.000000000002)

$2048 \ne 0$

# Практика 1

## Задача 1

відстань до трикутника
```
M(-1,-1)
A(1,1) B(2,3) C(4,-1)
AB(1,2) BC(2,-4) AC(3,-2)
```

1. Відстань від точки до вершин
$|MA|^2 = 8; \quad |MB|^2 = 21; \quad |MC|^2 = 25$

2. Відстань від точки до ребер
$Pr_{AB}AM = \frac{\vec{AB} \cdot \vec{AM}}{|\vec{AB}|^2} \cdot \vec{AB}$


In [26]:
M = np.array((-1,-1))
A = np.array((1,1))
B = np.array((2,3))
C = np.array((4,-1))
AB = np.array([1,2])
BC = np.array([2,-4])
AC = np.array([3,-2])

In [29]:
# project a onto b
def proj(a,b):
    return (a.dot(b) / b.dot(b)) * b

In [32]:
pr_ab_am = proj(M-A, AB)
pr_ab_am, np.linalg.det(np.c_[pr_ab_am, AB])

(array([-1.2, -2.4]), 0.0)

**todo: закінчити завдання**

# Задача 3

Про векторний добуток

Векторний добуток можна використовувати для орієнтування у просторі