In [1]:
import numpy as np
import scipy as sp

In [3]:
A = np.array([
    [1,2,3,4,5],
    [1,0,2,3,4],
    [2,-2,3,-3,5],
    [2,2,5,7,9],
])

In [5]:
m = A.mean(axis=1, keepdims=True)
m

array([[3.],
       [2.],
       [1.],
       [5.]])

In [6]:
A1 = A-m
A1

array([[-2., -1.,  0.,  1.,  2.],
       [-1., -2.,  0.,  1.,  2.],
       [ 1., -3.,  2., -4.,  4.],
       [-3., -3.,  0.,  2.,  4.]])

In [10]:
A2 = np.vstack([A1, np.array([1,1,1,1,1])])
A2

array([[-2., -1.,  0.,  1.,  2.],
       [-1., -2.,  0.,  1.,  2.],
       [ 1., -3.,  2., -4.,  4.],
       [-3., -3.,  0.,  2.,  4.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
np.linalg.matrix_rank(A1)

3

In [12]:
np.linalg.matrix_rank(A2)

4

**Центрування даних може змінити ранг матриці!**

---

Пошук перпендикулярних векторів

## Базова детермінантна тотожність

1. через алг доповнення

In [42]:
A = np.random.rand(3,5)-0.5
A

array([[ 0.39790035,  0.04706784,  0.23546001,  0.197155  ,  0.38792204],
       [-0.38346634, -0.17951208, -0.11114372, -0.22374939,  0.45615148],
       [-0.04671323,  0.07258026,  0.30465878, -0.44530662, -0.12196884]])

In [43]:
a1 = np.linalg.det(A[:, (1,2,3)]) * (-1)**(4+4)
a2 = np.linalg.det(A[:, (1,2,4)]) * (-1)**(4+3)
a3 = np.linalg.det(A[:, (1,3,4)]) * (-1)**(4+2)
a4 = np.linalg.det(A[:, (2,3,4)]) * (-1)**(4+1)
a5 = 0
r = np.array([a5,a4,a3,a2,a1])
A1 = np.vstack([A,r])
A1, np.linalg.matrix_rank(A1)

(array([[ 0.39790035,  0.04706784,  0.23546001,  0.197155  ,  0.38792204],
        [-0.38346634, -0.17951208, -0.11114372, -0.22374939,  0.45615148],
        [-0.04671323,  0.07258026,  0.30465878, -0.44530662, -0.12196884],
        [ 0.        , -0.12462326,  0.05036536,  0.02134897, -0.02629997]]),
 4)

In [44]:
A1 @ r

array([6.93889390e-18, 5.20417043e-18, 8.67361738e-19, 1.92150915e-02])

In [45]:
A1.dtype

dtype('float64')

In [46]:
a1 = np.linalg.det(A1[:, (0,1,2,3)]) * (-1)**(5+5)
a2 = np.linalg.det(A1[:, (0,1,2,4)]) * (-1)**(5+4)
a3 = np.linalg.det(A1[:, (0,1,3,4)]) * (-1)**(5+3)
a4 = np.linalg.det(A1[:, (0,2,3,4)]) * (-1)**(5+2)
a5 = np.linalg.det(A1[:, (1,2,3,4)]) * (-1)**(5+1)
r = np.array([a5,a4,a3,a2,a1])
A2 = np.vstack([A1,r])
A2, np.linalg.matrix_rank(A2)

(array([[ 3.97900347e-01,  4.70678359e-02,  2.35460007e-01,
          1.97154996e-01,  3.87922037e-01],
        [-3.83466340e-01, -1.79512077e-01, -1.11143718e-01,
         -2.23749386e-01,  4.56151484e-01],
        [-4.67132256e-02,  7.25802624e-02,  3.04658775e-01,
         -4.45306623e-01, -1.21968841e-01],
        [ 0.00000000e+00, -1.24623255e-01,  5.03653581e-02,
          2.13489661e-02, -2.62999651e-02],
        [ 1.92150915e-02, -9.88595368e-03, -1.76597419e-02,
         -1.57704219e-02,  2.24270077e-04]]),
 5)

In [47]:
A2 @ r

array([-5.20417043e-18,  5.20417043e-18, -2.16840434e-18, -6.50521303e-19,
        1.02757481e-03])

2. через фундаментальну систему розв'язків (todo)

In [26]:
B = np.array([
    [5, 10, 1],
    [7, 3, 1],
    [1, 2, 3],
])
B, np.linalg.det(B)

(array([[ 5, 10,  1],
        [ 7,  3,  1],
        [ 1,  2,  3]]),
 -154.00000000000006)

In [28]:
b1 = np.linalg.det(B[0:2, (1,2)]) * ((-1)**(3+1))
b2 = np.linalg.det(B[0:2, (0,2)]) * ((-1)**(3+2))
b3 = np.linalg.det(B[0:2, (0,1)]) * ((-1)**(3+3))
r1 = np.array([b1, b2, b3])
print(r1)
B1 = np.vstack([B[0:2,:], r1])
B1

[  7.   2. -55.]


array([[  5.,  10.,   1.],
       [  7.,   3.,   1.],
       [  7.,   2., -55.]])

In [29]:
B1 @ r1

array([-1.06581410e-14, -7.99360578e-15,  3.07800000e+03])

---

## Елементарні матриці


In [59]:
A = np.arange(16).reshape(4,4) + 1
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
# 1. обмін рядків

P = np.eye(4)
P[[0,1]] = P[[1,0]]
P

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
P @ A

array([[ 5.,  6.,  7.,  8.],
       [ 1.,  2.,  3.,  4.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [62]:
# 2. обмін стовпців

A @ P

array([[ 2.,  1.,  3.,  4.],
       [ 6.,  5.,  7.,  8.],
       [10.,  9., 11., 12.],
       [14., 13., 15., 16.]])

In [63]:
# 3. множення рядка на число

M = np.eye(4)
M[0] *= 100
M

array([[100.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0.,   1.,   0.],
       [  0.,   0.,   0.,   1.]])

In [64]:
M @ A

array([[100., 200., 300., 400.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.]])

In [65]:
# 4. множення стовпця на число

A @ M

array([[ 100.,    2.,    3.,    4.],
       [ 500.,    6.,    7.,    8.],
       [ 900.,   10.,   11.,   12.],
       [1300.,   14.,   15.,   16.]])

In [80]:
# 5. додавання рядка, помноженого на коефіцієнт, до іншого рядка

S = np.eye(4)
S[1,0] = 100
S

array([[  1.,   0.,   0.,   0.],
       [100.,   1.,   0.,   0.],
       [  0.,   0.,   1.,   0.],
       [  0.,   0.,   0.,   1.]])

In [81]:
S @ A

array([[  1.,   2.,   3.,   4.],
       [105., 206., 307., 408.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.]])

In [82]:
# 6. додавання стовпця, помноженого на коефіцієнт, до іншого стовпця

S1 = S.T
S1

array([[  1., 100.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0.,   0.,   1.,   0.],
       [  0.,   0.,   0.,   1.]])

In [83]:
(A @ S1).astype('int')

array([[   1,  102,    3,    4],
       [   5,  506,    7,    8],
       [   9,  910,   11,   12],
       [  13, 1314,   15,   16]])