In [2]:
import numpy as np
import scipy as sp

In [3]:
A = np.array([
    [1,2,3,4,5],
    [1,0,2,3,4],
    [2,-2,3,-3,5],
    [2,2,5,7,9],
])

In [5]:
m = A.mean(axis=1, keepdims=True)
m

array([[3.],
       [2.],
       [1.],
       [5.]])

In [6]:
A1 = A-m
A1

array([[-2., -1.,  0.,  1.,  2.],
       [-1., -2.,  0.,  1.,  2.],
       [ 1., -3.,  2., -4.,  4.],
       [-3., -3.,  0.,  2.,  4.]])

In [10]:
A2 = np.vstack([A1, np.array([1,1,1,1,1])])
A2

array([[-2., -1.,  0.,  1.,  2.],
       [-1., -2.,  0.,  1.,  2.],
       [ 1., -3.,  2., -4.,  4.],
       [-3., -3.,  0.,  2.,  4.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
np.linalg.matrix_rank(A1)

3

In [12]:
np.linalg.matrix_rank(A2)

4

**Центрування даних може змінити ранг матриці!**

---

Пошук перпендикулярних векторів

1. через алг доповнення

In [14]:
A = np.floor(np.random.rand(3,5)*100 - 50)
A

array([[ 27., -23.,  30.,  17., -30.],
       [ 32.,  43., -12.,  17.,  33.],
       [ 37., -49., -48.,  10., -11.]])

In [15]:
a1 = np.linalg.det(A[:, (1,2,3)])
a2 = np.linalg.det(A[:, (1,2,4)])
a3 = np.linalg.det(A[:, (1,3,4)])
a4 = np.linalg.det(A[:, (2,3,4)])
a5 = 0
r = np.array([a5,a4,a3,a2,a1])
A1 = np.vstack([A,r])
A1, np.linalg.matrix_rank(A1)

(array([[ 2.7000e+01, -2.3000e+01,  3.0000e+01,  1.7000e+01, -3.0000e+01],
        [ 3.2000e+01,  4.3000e+01, -1.2000e+01,  1.7000e+01,  3.3000e+01],
        [ 3.7000e+01, -4.9000e+01, -4.8000e+01,  1.0000e+01, -1.1000e+01],
        [ 0.0000e+00, -6.5562e+04, -4.5447e+04,  5.7720e+03, -9.8982e+04]]),
 4)

In [16]:
a1 = np.linalg.det(A1[:, (0,1,2,3)])
a2 = np.linalg.det(A1[:, (0,1,2,4)])
a3 = np.linalg.det(A1[:, (0,1,3,4)])
a4 = np.linalg.det(A1[:, (0,2,3,4)])
a5 = np.linalg.det(A1[:, (1,2,3,4)])
r = np.array([a5,a4,a3,a2,a1])
A2 = np.vstack([A1,r])
A2, np.linalg.matrix_rank(A2)

(array([[ 2.70000000e+01, -2.30000000e+01,  3.00000000e+01,
          1.70000000e+01, -3.00000000e+01],
        [ 3.20000000e+01,  4.30000000e+01, -1.20000000e+01,
          1.70000000e+01,  3.30000000e+01],
        [ 3.70000000e+01, -4.90000000e+01, -4.80000000e+01,
          1.00000000e+01, -1.10000000e+01],
        [ 0.00000000e+00, -6.55620000e+04, -4.54470000e+04,
          5.77200000e+03, -9.89820000e+04],
        [ 7.53117431e+09, -2.67122798e+09,  6.81464226e+08,
          1.47413148e+10, -2.94183208e+09]]),
 5)

2. через фундаментальну систему розв'язків (todo)

---

метод якобі пошуку оберненої матриці