In [3]:
import numpy as np

def _(*args, **kwargs):
    return np.array([*args], **kwargs)

# Практика 3
Корешков

```

Задача#1
Знайти розв'язок системи A x =  B методом Гауса, де 

A = {{-3, -8, 3}, {3, -9, -9}, {2, -5, -1}}; B = {5, 7, 0};
A = {{-0.160, 5.603, 8.948}, {-9.494, 1.255, -5.962}, {6.870, -6.467,  2.035}};  B = {9.957, -4.966, 3.032};
виконуючи обчислення з п'ятьма значущими цифрами.

Задача#2
Знайти матрицю обернену до матриці A #1

Задача#3
Визначити число обумовленості матриці A #1
```

## Задача 1

Спочатку наведу реалізацію метода Гауса з вибором ведучого елемента.  
Але я реалізую не функцію розв'язку рівняння за відомою матрицею та вільним членом, а окремо функцію LU-факторизації, і окремо функцію для прямого та зворотнього ходів.


Опис алгоритму. Розглянемо покроково суть гаусового алгоритму з точки зору матриць.  

1. **Ділення рядка на число через множення на матрицю**  
    $$\begin{pmatrix}
    a_{11} & a_{12} & a_{13}\\
    a_{21} & a_{22} & a_{23}\\
    a_{31} & a_{32} & a_{33}
    \end{pmatrix} 
    \longrightarrow
    \begin{pmatrix}
    \frac{a_{11}}{a_{11}} & \frac{a_{12}}{a_{11}} & \frac{a_{13}}{a_{11}}\\
    a_{21} & a_{22} & a_{23}\\
    a_{31} & a_{32} & a_{33}
    \end{pmatrix} 
    $$
    Еквівалентно наступному множенню  
    $$\begin{pmatrix}
    \frac{1}{a_{11}} & 0 & 0 \\
    0 & 1 & 0\\
    0 & 0 & 1
    \end{pmatrix} \cdot 
    \begin{pmatrix}
    a_{11} & a_{12} & a_{13}\\
    a_{21} & a_{22} & a_{23}\\
    a_{31} & a_{32} & a_{33}
    \end{pmatrix} = 
    \begin{pmatrix}
    1 & \frac{a_{12}}{a_{11}} & \frac{a_{13}}{a_{11}}\\
    a_{21} & a_{22} & a_{23}\\
    a_{31} & a_{32} & a_{33}
    \end{pmatrix} 
    $$

2. **Наступне віднімання рядка від всіх інших, пропорційно першому елементу**
    $$\begin{pmatrix}
    a_{11} & a_{12} & a_{13}\\
    a_{21} & a_{22} & a_{23}\\
    a_{31} & a_{32} & a_{33}
    \end{pmatrix} 
    \longrightarrow
    \begin{pmatrix}
    1 & \frac{a_{12}}{a_{11}} & \frac{a_{13}}{a_{11}}\\
    0 & a_{22}-a_{21}\cdot\frac{a_{12}}{a_{11}} & a_{23}-a_{21}\cdot\frac{a_{12}}{a_{11}}\\
    0 & a_{32}-a_{31}\cdot\frac{a_{12}}{a_{11}} & a_{33}-a_{31}\cdot\frac{a_{12}}{a_{11}}
    \end{pmatrix} 
    $$
    Еквівалентно наступному множенню  
    $$\begin{pmatrix}
    \frac{1}{a_{11}} & 0 & 0 \\
    -\frac{a_{21}}{a_{11}} & 1 & 0\\
    -\frac{a_{31}}{a_{11}} & 0 & 1
    \end{pmatrix} \cdot 
    \begin{pmatrix}
    a_{11} & a_{12} & a_{13}\\
    a_{21} & a_{22} & a_{23}\\
    a_{31} & a_{32} & a_{33}
    \end{pmatrix} = 
    \begin{pmatrix}
    1 & \frac{a_{12}}{a_{11}} & \frac{a_{13}}{a_{11}}\\
    0 & a_{22} & a_{23}\\
    0 & a_{32} & a_{33}
    \end{pmatrix} 
    $$

3. **Наступна ітерація**  
    $$
    \begin{pmatrix}
    1 & 0 & 0 \\
    0 & \frac{1}{c} & 0\\
    0 & -\frac{e}{c} & 1
    \end{pmatrix} \cdot 
    \begin{pmatrix}
    1 & a & b\\
    0 & c & d\\
    0 & e & f
    \end{pmatrix} = 
    \begin{pmatrix}
    1 & a & b\\
    0 & 1 & d'\\
    0 & 0 & f'
    \end{pmatrix} 
    $$

4. **Комбінація двох ітерацій**  
    $$
    \begin{pmatrix}
    1 & 0 & 0 \\
    0 & \frac{1}{b_{22}} & 0\\
    0 & -\frac{b_{32}}{b_{22}} & 1
    \end{pmatrix} \cdot 
    \begin{pmatrix}
    \frac{1}{a_{11}} & 0 & 0 \\
    -\frac{a_{21}}{a_{11}} & 1 & 0\\
    -\frac{a_{31}}{a_{11}} & 0 & 1
    \end{pmatrix} \cdot 
    \begin{pmatrix}
    a_{11} & a_{12} & a_{13}\\
    a_{21} & a_{22} & a_{23}\\
    a_{31} & a_{32} & a_{33}
    \end{pmatrix} = 
    \begin{pmatrix}
    1 & \frac{a_{12}}{a_{11}} & \frac{a_{13}}{a_{11}}\\
    0 & 1 & \frac{b_{23}}{b_{22}}\\
    0 & 0 & a_{33}-a_{32}\frac{b_{23}}{b_{22}}
    \end{pmatrix}
    $$

    Результуюча ліва матриця
    $$
    \begin{pmatrix}
    \frac{1}{a_{11}} & 0 & 0 \\
    -\frac{a_{21}}{a_{11}b_{22}} & \frac{1}{b_{22}} & 0\\
    -\frac{a_{31}}{a_{11}}+\frac{b_{32}}{b_{22}}\cdot\frac{a_{21}}{a_{11}} & -\frac{b_{32}}{b_{22}} & 1
    \end{pmatrix}
    $$

5. **Остання ітерація**  
    Результуюча ліва матриця
    $$
    \begin{pmatrix}
    \frac{1}{a_{11}} & 0 & 0 \\
    -\frac{a_{21}}{a_{11}}\cdot\frac{1}{b_{22}} & \frac{1}{b_{22}} & 0\\
    -\frac{a_{31}}{a_{11}}\cdot\frac{1}{c_{33}}+\frac{b_{32}}{b_{22}}\cdot\frac{a_{21}}{a_{11}}\cdot\frac{1}{c_{33}} & -\frac{b_{32}}{b_{22}}\cdot\frac{1}{c_{33}} & \frac{1}{c_{33}}
    \end{pmatrix}
    $$

Тобто, кожну наступну ітерацію треба виконувати на лівій матриці такі самі операції, що і на правій.


In [6]:
A = _([10,2,3],[4,5,6],[7,8,9])
print("A:")
print(A)

M1 = _([1/10, 0, 0], [-4/10, 1, 0], [-7/10,0,1])
print("M1:")
print(M1)

A = M1 @ A
print("M1 * A:")
print(A)

M2 = _([1, 0, 0], [0, 1/A[1,1], 0], [0, -A[2,1]/A[1,1], 1])
print("M2:")
print(M2)

A = M2 @ A
print("M2 * M1 * A:")
print(A)

print("M2 * M1:")
print(M2 @ M1)

M3 = _([1,0,0],[0,1,0],[0,0,1/A[2,2]])
print("M3:")
print(M3)

A = M3 @ A
print("M3 * M2 * A:")
print(A)

print("M3 * M2 * M1:")
print(M3@M2@M1)

A:
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
M1:
[[ 0.1  0.   0. ]
 [-0.4  1.   0. ]
 [-0.7  0.   1. ]]
M1 * A:
[[1.  0.2 0.3]
 [0.  4.2 4.8]
 [0.  6.6 6.9]]
M2:
[[ 1.          0.          0.        ]
 [ 0.          0.23809524  0.        ]
 [ 0.         -1.57142857  1.        ]]
M2 * M1 * A:
[[ 1.          0.2         0.3       ]
 [ 0.          1.          1.14285714]
 [ 0.          0.         -0.64285714]]
M2 * M1:
[[ 0.1         0.          0.        ]
 [-0.0952381   0.23809524  0.        ]
 [-0.07142857 -1.57142857  1.        ]]
M3:
[[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.         -1.55555556]]
M3 * M2 * A:
[[1.         0.2        0.3       ]
 [0.         1.         1.14285714]
 [0.         0.         1.        ]]
M3 * M2 * M1:
[[ 0.1         0.          0.        ]
 [-0.0952381   0.23809524  0.        ]
 [ 0.11111111  2.44444444 -1.55555556]]


In [7]:
L = M3@M2@M1
Linv = np.linalg.inv(L)
print("Linv:")
print(Linv)

Linv:
[[ 1.00000000e+01 -2.36255460e-14  4.71278345e-16]
 [ 4.00000000e+00  4.20000000e+00  3.62521804e-17]
 [ 7.00000000e+00  6.60000000e+00 -6.42857143e-01]]


Особливість трикутної матриці в тому, що її обернена також трикутна того ж виду

## Суть факторизації
$$Ax=b$$
$$LA=U;\quad A = L^{-1}U = L_1 U$$
$$LAx=Lb$$
$$Ux=Lb$$
$$x=U^{-1}Lb$$

$Lb$ обчислюється очевидно, $x$ обчислюється зручно та без необхідності пошуку зворотньої матриці $U^{-1}$ в явному вигляді. 

Як працювати з обміном рядками?

$$Ax=b$$
$$PLA=U_{permuted}$$
$$PLAx=PLb$$
$$U_{permuted}x=PLb$$

При чому замість $L$ можна одразу зберігати $L_{permuted}=PL$

$$U_{perm}x=L_{perm}b$$

In [94]:
# метод гауса для квадратних матриць
def LU(A, D=4):
    n = A.shape[0]
    if A.shape[0] != A.shape[1]: raise ValueError("Matrix A is not square")
    if len(A.shape) != 2: raise ValueError("A is not a matrix")
    
    # output
    L = np.eye(n) # lower triangular
    U = A.copy()  # upper triangular
    perm = np.arange(n) # row permutation

    # offset
    k = 0

    
    print("init")
    print("U:")
    print(U)
    print("L:")
    print(L)
    
    while k < n-1:
        # find the largest element in current column below the diagonal
        M, absM = U[k,k], np.abs(U[k,k])
        Mi = k
        for i in range(k+1,n):
            a = np.abs(U[i,k])
            if a > absM: 
                absM, M, Mi = a, U[i,k], i
        
        # we want to permute rows of the matrix in
        #   a such way that the largest element becomes the top left
        #   corner of not processed elements

        # M is the pivot element value
        print("pivot row = ", Mi)
        # permute U and perm
        r1, r2 = U[k], U[Mi]
        U[k], U[Mi] = r2.copy(), r1.copy()
        r1, r2 = L[:,k], L[:,Mi]
        L[:,k], L[:,Mi] = r2.copy(), r1.copy()
        perm[k], perm[Mi] = perm[Mi], perm[k]

        print("swap rows and cols")
        print("U:")
        print(U)
        print("L:")
        print(L)
        print("perm:")
        print(perm)

        # M is a pivot element
        # PC is a pivot column
        PC = U[(k+1):,k].copy()

        # divide first row by pivot element
        U[k] = (U[k] / M).round(D)
        L[k] = (L[k] / M).round(D)
        # substract first row from other rows
        U[(k+1):] = (U[(k+1):] - (U[k]*PC[:,None])).round(D)
        L[(k+1):] = (L[(k+1):] - (L[k]*PC[:,None])).round(D)

        print("subtract")
        print("U:")
        print(U)
        print("L:")
        print(L)
        
        k += 1
    
    L[-1,-1] = np.round(1/U[-1,-1], D)
    U[-1,-1] = 1

    print("final")
    print("U:")
    print(U)
    print("L:")
    print(L)
    print("perm:")
    print(perm)

    return L,U,perm


def apply_L(L, b, D=4):
    return np.round(L @ b, D)

def invert_U(U, b, D=4):
    n = U.shape[1]
    x = np.zeros(n)
    x[n-1] = (b[n-1] / U[n-1,n-1]).round(D)
    for i in range(n-2, -1, -1):
        x[i] = ((b[i] - U[i,i+1:] @ x[i+1:]) / U[i,i]).round(D)
    return x
    


In [46]:
# Sanity check функції invert_U
U = np.triu(np.random.rand(4,4))
x0 = np.random.rand(4)
b = U @ x0
x = invert_U(U,b, D=20)

print(x - x0)

[1.11022302e-16 1.11022302e-16 0.00000000e+00 0.00000000e+00]


In [95]:
# Sanity check розкладу
A = np.random.rand(4,4)*2 - 1
x0 = np.random.rand(4)*2 - 1
b = A@x0

L,U,p = LU(A, D=20)
b1 = apply_L(L, b, D=20)
b2 = b1[p]
x = invert_U(U, b2, D=20)

print()
print("x-x0:")
print(x-x0)

init
U:
[[ 0.80069802  0.12728225  0.46068953 -0.5471121 ]
 [-0.39415539  0.96861675 -0.59805222 -0.18132456]
 [-0.43484418  0.94221742  0.17911495 -0.50038229]
 [-0.94834258 -0.50963916 -0.77282861  0.06518757]]
L:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
pivot row =  3
swap rows and cols
U:
[[-0.94834258 -0.50963916 -0.77282861  0.06518757]
 [-0.39415539  0.96861675 -0.59805222 -0.18132456]
 [-0.43484418  0.94221742  0.17911495 -0.50038229]
 [ 0.80069802  0.12728225  0.46068953 -0.5471121 ]]
L:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
perm:
[3 1 2 0]
subtract
U:
[[ 1.          0.53739985  0.81492557 -0.06873842]
 [ 0.          1.1804358  -0.27684492 -0.20841817]
 [ 0.          1.17590262  0.53348059 -0.53027279]
 [ 0.         -0.30301275 -0.19181975 -0.49207339]]
L:
[[-0.         -0.         -0.         -1.05447127]
 [ 0.          1.          0.         -0.41562553]
 [ 0.          0.          1.         -0.45853069]
 [ 1.          0.          0

In [88]:
b

array([ 0.31857898,  0.16499488, -0.44555932, -0.47984098, -0.18701904])

In [89]:
L@b

array([ 0.40128322, -0.52806802, -0.22698176, -0.90389597,  0.07952686])

In [90]:
U@x0

array([ 0.20782814, -0.68482927, -0.20097624, -1.05506604,  0.50598735])